"""Self-contained HTML dashboard.

No external stylesheets, fonts, scripts, or CDN calls. A report is often opened
from a CI artifact on a machine with no network access, and a dashboard that needs
to phone out to render is a dashboard that shows a blank page.

Everything is escaped: failure messages come from test output, which is
attacker-controlled in the general case.
"""

from __future__ import annotations

from html import escape

from ..models import AnalysisReport, TestAnalysis, Verdict

POSITION_DETAIL_THRESHOLD = 0.5
"""Below this, position separation is supporting detail not worth printing."""

_STYLE = """
:root {
  --bg: #ffffff; --fg: #1a1a1a; --muted: #6b7280; --line: #e5e7eb;
  --flaky: #b45309; --regression: #b91c1c; --broken: #7f1d1d;
  --fixed: #15803d; --stable: #9ca3af; --accent: #1d4ed8;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0f1115; --fg: #e5e7eb; --muted: #9ca3af; --line: #262b36;
    --flaky: #fbbf24; --regression: #f87171; --broken: #fca5a5;
    --fixed: #4ade80; --stable: #6b7280; --accent: #60a5fa;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem 1.5rem; background: var(--bg); color: var(--fg);
  font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
}
main { max-width: 1100px; margin: 0 auto; }
h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
h2 { font-size: 1.1rem; margin: 2.25rem 0 .75rem; }
.sub { color: var(--muted); margin: 0 0 1.5rem; font-size: .9rem; }
.cards { display: flex; flex-wrap: wrap; gap: .75rem; margin-bottom: 1.5rem; }
.card {
  border: 1px solid var(--line); border-radius: 8px; padding: .6rem .9rem; min-width: 92px;
}
.card .n { font-size: 1.5rem; font-weight: 600; }
.card .l { color: var(--muted); font-size: .75rem; text-transform: uppercase;
           letter-spacing: .04em; }
table { width: 100%; border-collapse: collapse; font-size: .875rem; }
th, td { text-align: left; padding: .45rem .6rem; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-weight: 600; font-size: .72rem; text-transform: uppercase;
     letter-spacing: .04em; }
td.n, th.n { text-align: right; font-variant-numeric: tabular-nums; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .82em;
       word-break: break-all; }
.v { font-weight: 600; font-size: .78rem; }
.v-flaky { color: var(--flaky); } .v-regression { color: var(--regression); }
.v-broken { color: var(--broken); } .v-fixed { color: var(--fixed); }
.v-stable { color: var(--stable); }
.bar { height: 4px; border-radius: 2px; background: var(--line); overflow: hidden;
       min-width: 44px; }
.bar > i { display: block; height: 100%; background: var(--flaky); }
.note { border-left: 3px solid var(--flaky); padding: .7rem .9rem;
        background: color-mix(in srgb, var(--flaky) 8%, transparent);
        border-radius: 0 6px 6px 0; margin: 1.25rem 0; font-size: .875rem; }
details { margin: .5rem 0; }
summary { cursor: pointer; color: var(--accent); font-size: .875rem; }
.diag { border: 1px solid var(--line); border-radius: 8px; padding: .8rem 1rem; margin: .6rem 0; }
.diag h3 { margin: 0 0 .5rem; font-size: .9rem; }
.diag ul { margin: .35rem 0 0; padding-left: 1.1rem; color: var(--muted); font-size: .85rem; }
footer { margin-top: 3rem; color: var(--muted); font-size: .78rem;
         border-top: 1px solid var(--line); padding-top: .9rem; }
"""


def render_report(report: AnalysisReport, *, limit: int = 100) -> str:
    """Render a standalone HTML document."""
    rows = [t for t in report.tests if t.verdict is not Verdict.STABLE][:limit]

    parts: list[str] = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>Flaky test report</title>",
        f"<style>{_STYLE}</style>",
        "</head>",
        "<body><main>",
        "<h1>Flaky test report</h1>",
        f'<p class="sub">{_window(report)}</p>',
        _cards(report),
    ]

    if not report.has_commit_data:
        parts.append(
            '<p class="note"><strong>Weak evidence.</strong> No run carried a commit '
            "SHA, so same-commit divergence could not be measured. These scores rest "
            "on flip rate alone, which is a weaker signal.</p>"
        )

    if rows:
        parts.append("<h2>Ranked tests</h2>")
        parts.append(_tests_table(rows))
        parts.append(_diagnosis(rows))
    else:
        parts.append("<p>No flaky tests, regressions, or broken tests found.</p>")

    parts.append(_clusters(report))
    parts.append(
        "<footer>Generated by flaky-test-detective. Scores combine same-commit "
        "divergence (proof) with flip rate (inference), damped by run count. "
        "Root-cause categories are heuristics: the matched terms are shown so they "
        "can be checked.</footer>"
    )
    parts.append("</main></body></html>")
    return "\n".join(parts) + "\n"


def _window(report: AnalysisReport) -> str:
    window = ""
    if report.window_start and report.window_end:
        window = f" &middot; {escape(report.window_start[:10])} to {escape(report.window_end[:10])}"
    return (
        f"{report.total_runs} runs &middot; {report.total_results} results &middot; "
        f"{len(report.tests)} tests{window}"
    )


def _cards(report: AnalysisReport) -> str:
    cards = [
        ("flaky", len(report.flaky), "flaky"),
        ("regression", len(report.regressions), "regression"),
        ("broken", len(report.broken), "broken"),
        ("fixed", len(report.fixed), "fixed"),
    ]
    inner = "".join(
        f'<div class="card"><div class="n v-{css}">{count}</div>'
        f'<div class="l">{escape(label)}</div></div>'
        for label, count, css in cards
    )
    return f'<div class="cards">{inner}</div>'


def _tests_table(tests: list[TestAnalysis]) -> str:
    head = (
        "<thead><tr>"
        '<th class="n">Score</th><th></th><th>Verdict</th><th class="n">Runs</th>'
        '<th class="n">Pass</th><th class="n">Fail</th><th class="n">Flips</th>'
        '<th class="n">Same-commit</th><th>Cause</th><th>Test</th>'
        "</tr></thead>"
    )

    body: list[str] = []
    for test in tests:
        divergence = (
            f"{test.divergent_commits}/{test.observed_commits}"
            if test.observed_commits
            else "&ndash;"
        )
        cause = escape(str(test.cause.cause)) if test.cause else ""
        width = round(test.score * 100)
        body.append(
            "<tr>"
            f'<td class="n">{test.score:.2f}</td>'
            f'<td><div class="bar"><i style="width:{width}%"></i></div></td>'
            f'<td class="v v-{escape(str(test.verdict))}">{escape(str(test.verdict))}</td>'
            f'<td class="n">{test.runs}</td>'
            f'<td class="n">{test.passes}</td>'
            f'<td class="n">{test.failures}</td>'
            f'<td class="n">{test.flips}</td>'
            f'<td class="n">{divergence}</td>'
            f"<td>{cause}</td>"
            f"<td><code>{escape(test.test_id)}</code></td>"
            "</tr>"
        )

    return f"<table>{head}<tbody>{''.join(body)}</tbody></table>"


def _diagnosis(tests: list[TestAnalysis], limit: int = 8) -> str:
    interesting = [t for t in tests if t.verdict is Verdict.FLAKY and t.cause is not None][:limit]
    if not interesting:
        return ""

    blocks: list[str] = ["<h2>Diagnosis</h2>"]
    for test in interesting:
        assert test.cause is not None
        points: list[str] = []

        if test.order is not None:
            if test.order.likely_polluter:
                points.append(
                    f"<strong>Order dependent</strong>: fails after "
                    f"<code>{escape(test.order.likely_polluter)}</code> in "
                    f"{test.order.polluter_failure_share:.0%} of its failures."
                )
            if test.order.separation >= POSITION_DETAIL_THRESHOLD:
                points.append(
                    f"Also runs later when it fails: position "
                    f"{test.order.mean_position_on_fail:.0f} on average versus "
                    f"{test.order.mean_position_on_pass:.0f} when passing."
                )
        elif test.cause.matched:
            terms = ", ".join(f"<code>{escape(m)}</code>" for m in test.cause.matched)
            points.append(f"Likely <strong>{escape(str(test.cause.cause))}</strong> ({terms}).")

        points.append(escape(test.cause.remediation))
        if test.representative_message:
            points.append(
                f"Example: <code>{escape(_one_line(test.representative_message, 200))}</code>"
            )

        items = "".join(f"<li>{p}</li>" for p in points)
        blocks.append(
            f'<div class="diag"><h3><code>{escape(test.test_id)}</code></h3><ul>{items}</ul></div>'
        )

    return "".join(blocks)


def _clusters(report: AnalysisReport, limit: int = 15) -> str:
    shared = [c for c in report.clusters if c.test_count > 1][:limit]
    if not shared:
        return ""

    rows = "".join(
        "<tr>"
        f'<td class="n">{c.test_count}</td>'
        f'<td class="n">{c.failure_count}</td>'
        f"<td>{escape(str(c.cause.cause)) if c.cause else ''}</td>"
        f"<td><code>{escape(_one_line(c.signature, 160))}</code></td>"
        "</tr>"
        for c in shared
    )
    return (
        "<h2>Shared failure signatures</h2>"
        '<p class="sub">One cause, several tests. Usually the cheapest thing to fix.</p>'
        '<table><thead><tr><th class="n">Tests</th><th class="n">Failures</th>'
        "<th>Cause</th><th>Signature</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def _one_line(text: str, width: int = 120) -> str:
    collapsed = " ".join(text.split())
    return collapsed if len(collapsed) <= width else collapsed[: width - 3] + "..."
